SEED: 1337 # random seed for reproduce results
DATA_ROOT: '/nfs/zzzhong/codes/exp/workspace_yc/dataset/MS1Mv2' # parent directory of images folder
INDEX_ROOT: '/nfs/zzzhong/codes/exp/TFace/recognition/indexes' # parent directory of image list files
DATASET_MODE: 'image_list' # options: auto/image_list
IMAGE_EXTENSIONS: ['.jpg', '.jpeg', '.png']
DATASETS:
    - name: MS1Mv2_namelist
      batch_size: 128
      weight: 1.0
      scale: 64
      margin: 0.4

BACKBONE_RESUME: ""
HEAD_RESUME: ""
META_RESUME: ""

INPUT_SIZE: [112, 112]
BACKBONE_NAME: 'IR_50'
EMBEDDING_SIZE: 512

MODEL_ROOT: './ckpt/baseline'
LOG_ROOT: './tensorboard'

DIST_FC: true
HEAD_NAME: "ArcFace"
LOSS_NAME: 'DistCrossEntropy'

RGB_MEAN: [0.5, 0.5, 0.5]
RGB_STD: [0.5, 0.5, 0.5]

LRS: [0.1, 0.01, 0.001, 0.0001, 0.00001]
WARMUP_STEP: -1
STAGES: [8, 12, 15, 18]

START_EPOCH: 0
NUM_EPOCH: 20
SAVE_EPOCHS: [1, 15, 18, 20]

WEIGHT_DECAY: 0.0005
MOMENTUM: 0.9

WORLD_SIZE: 1
RANK: 0
LOCAL_RANK: 0
DIST_BACKEND: 'nccl'
DIST_URL: 'env://'

NUM_WORKERS: 32

AMP: true
